### ISSUE TITLE
Set up your Kanban: Code review

### ISSUE THREAD

**Issue by EvansSnave** [EvansSnave/final-capstone-project-front-end#17]
**Links**

1. Link to front-end kanban [here](https://github.com/EvansSnave/final-capstone-project-front-end/projects/1)
2. Link to back-end kanban [here](https://github.com/EvansSnave/final-capstone-project-back-end/projects/1)

**Students**

- Student A: Kevin Cruz || @EvansSnave
- Student B: Fisayo Michael || @fmanimashaun

**Kanban**

- Back-end:

![back-end-kanban](https://github.com/EvansSnave/final-capstone-project-front-end/assets/127534196/47fb194e-e2a0-4ebb-be24-9321c37f82d1)

- Front-end: 

![front-end-kanban](https://github.com/EvansSnave/final-capstone-project-front-end/assets/127534196/31c7d998-feec-4558-82ee-ab36a1e6758c)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
